#!/usr/bin/python3
# Copyright 2016 Joel Stanley <joel@jms.id.au>
# Apache 2.0

def num_to_gpio(num):
    num = int(num) % 320
    v = num // 8
    first = v // 26
    second = v % 26
    bank = chr(second + ord('a'))
    if first > 0:
       bank = chr(first - 1 + ord('a')) + chr(second + ord('a'))

    index = num % 8

    return (bank, index)

if __name__ == '__main__':
   import sys
   gpio = num_to_gpio(sys.argv[1])
   print("GPIO{}{}".format(gpio[0].upper(), gpio[1]))

