#!/bin/sh
#
# Copyright 2016 Andrew Jeffery <andrew@aj.id.au>
# Apache 2.0
#
# Sets all GPIOs to high and low ensuring that the value takes hold
#

set -eu

GPIO_BASE=320
GPIO_NR=191
GPIO_SYSFS=/sys/class/gpio

for i in $(seq ${GPIO_BASE} $((${GPIO_BASE} + ${GPIO_NR})))
do
    if ! echo ${i} > ${GPIO_SYSFS}/export
    then
	echo Failed to export gpio${i}
	continue
    fi
    RESULT=0
    echo out > ${GPIO_SYSFS}/gpio${i}/direction
    echo 1 > ${GPIO_SYSFS}/gpio${i}/value
    [ 1 -eq $( cat ${GPIO_SYSFS}/gpio${i}/value ) ] || true
    RESULT=$((${RESULT} + $?))
    echo 0 > ${GPIO_SYSFS}/gpio${i}/value
    [ 0 -eq $( cat ${GPIO_SYSFS}/gpio${i}/value ) ] || true
    RESULT=$((${RESULT} + $?))
    if [ 0 -eq ${RESULT} ]
    then
	echo ${i} > ${GPIO_SYSFS}/unexport
    else
	echo Failed to toggle gpio${i}
    fi
done
